import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { AppWarpper } from "@/components/AppWarpper"

const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "MENU JUY",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <RouterProvider router={route}/>
    <html lang="en">
      <body className={inter.className}>
        <AppWarpper>
          {children}
        </AppWarpper>
      </body>
    </html>
  );
}
